<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns0="http://TargetNamespace.com/ServiceName"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="nxsd_clientb1_schema.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClientB1" namespace="http://TargetNamespace.com/ServiceName"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="nxsd_scb_schema1.xsd"/>
            <oracle-xsl-mapper:rootElement name="SCBStandard1" namespace="http://TargetNamespace.com/ServiceName"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JUL 08 15:15:10 ICT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:SCBStandard1>
         <xsl:for-each select="/ns0:ClientB1/ns0:Transaction">
            <ns0:Transaction>
               <ns0:No>
                  <xsl:value-of select="ns0:no"/>
               </ns0:No>
               <ns0:AccountName>
                  <xsl:value-of select="ns0:acct_name"/>
               </ns0:AccountName>
               <ns0:AccountNo>
                  <xsl:value-of select="ns0:acct_no"/>
               </ns0:AccountNo>
               <ns0:Amount1>
                  <xsl:value-of select="ns0:amt1"/>
               </ns0:Amount1>
               <ns0:Bank>
                  <xsl:value-of select="ns0:bank"/>
               </ns0:Bank>
               <ns0:Contacts>
                  <xsl:value-of select="ns0:contacts"/>
               </ns0:Contacts>
               <ns0:BeneficiaryCharge>
                  <xsl:value-of select="ns0:beneficiary"/>
               </ns0:BeneficiaryCharge>
               <ns0:Fee>
                  <xsl:value-of select="ns0:fee"/>
               </ns0:Fee>
               <ns0:NetAmount>
                  <xsl:value-of select="ns0:net_amt"/>
               </ns0:NetAmount>
            </ns0:Transaction>
         </xsl:for-each>
      </ns0:SCBStandard1>
   </xsl:template>
</xsl:stylesheet>
